version: "3.6"

services:
  detectron2:
    build:
      context: Docker/
      dockerfile: Dockerfile
    runtime: nvidia
    shm_size: "8gb"
    ports:
      - "6006:6006"
      - "8888:8888"
    volumes:
      - type: bind
        source: ./
        target: /application
    environment:
            - NVIDIA_VISIBLE_DEVICES=all
